### ISSUE TITLE
Make device configurable using the resistors

### ISSUE THREAD

**Issue by CShark** [CShark/usb_dmx#1]
The Input & Output configuration should be configurable using the resistors. Add support.

**Comment by Flole998** [comment]
@CShark What do you think about extending this a little to allow setting the configuration over USB/ArtNet/UDP packets and storing it in the EEPROM? If at boot a valid EEPROM entry with a matching checksum is found the resistors are ignored and the EEPROM setting is used instead. That sounds like a good idea to me, what do you think?

**Comment by CShark** [comment]
Already (semi) done. The resistors will supply the default configuration after a config reset and you can use the Command field of the ArtAddress-Packet to overwrite the settings. Settings are currently (i.e. in the upcoming version) stored in a flash page at the end of the device.

The current version should be functionally done, I'm currently writing the tooling to manipulate and configure ArtNET devices. The latest ETA for a working implementation will be this easter, as I'll need it working by then :D
